### ISSUE TITLE
new masterchef sushi-eth deposit token link is different than jar format

### ISSUE THREAD

**Issue by robstryker** [pickle-finance/pickle-ui#102]
MC2Farm.tsx linking new masterchef pickle-eth deposit url as https://analytics.sushi.com/pairs/0x269db91fc3c7fcc275c2e6f22e5552504512811c

Most jars use the following pattern for deposit tokens: https://app.sushi.com/add/0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b/ETH

We should standardize on one format or the other, not mix and match. Should we link to add-liquidity? Or pair data?

**Comment by robstryker** [comment]
Also it seems a lot of the existing urls (ex: https://exchange.sushiswapclassic.org/#/add/0x6b175474e89094c44da98b954eedeac495271d0f/ETH)  do not work. They redirect to a swap page (not add) and the non-eth token never loads.

**Comment by mannyreimi88** [comment]
fixed with #105
