### ISSUE TITLE
User previously approved deposit to jar, now makes bigger deposit, deposit fails, no fix offered

### ISSUE THREAD

**Issue by robstryker** [pickle-finance/pickle-ui#126]
cstampar
 — 
Today at 2:22 PM
so i went to deposit some USDC into the pYUSDC jar....a few months ago i set an approval limit when i first deposited, which i forgot about, and i was trying to deposit more than what i had approved. the pJar catches this error, but the "deposit" button just flashes to "depositing" quickly and then nothing happens. i had to figure out what the error was, with some help from you all, but the UI doesn't inform you, or give you a way to increase your approval limit, so without direct contract interaction, there is no way on Pickle to increase your spending limit so you can deposit more into a jar. I first tried calling approve() and increaseAllowance() on the pJar contract, but that was only increasing the spend limit for pUSDC, not USDC itself, so i was still limited and not allowed to deposit anymore to the jar. the solution was to go on etherscan to the USDC contract and "write as proxy" and call approve() with my eth address as owner and the pJar contract as spender, which effectively increased my USDC spend limit and i was able to deposit all that i wanted to the pJar and farm :Thumb:

my suggestion is (1) when a user tries to deposit more than they have previously approved, a message should pop up informing that the user is exceeding their approval limit (2) it should provide a button which calls the approve() function on each jars underlying token so the user can increase their limit and deposit as they please to pickle :PepePray: @bwar  @Sevenz @Larry the Cucumber @Cipio

**Comment by robstryker** [comment]
Second user complaining on this issue:

https://discord.com/channels/750784472697405646/755579429320654899/884292877369344031

https://discord.com/channels/750784472697405646/755579429320654899/884582835355258950

**Comment by robstryker** [comment]
Issue is likely caused because JAR_renCRV does not have a farm, and farms.tsx logic presents by gauge. 

pjar 0c and pjar 0d are both visible but they have farms. pjar 0a is not visible but it is disabled.

**Comment by rawbdor** [comment]
Third user complaining on this issue. https://discord.com/channels/750784472697405646/755579429320654899/927336523207176243
