### ISSUE TITLE
sushi jars do not show LP fees

### ISSUE THREAD

**Issue by robstryker** [pickle-finance/pickle-ui#128]
Sushi jars and Uniswap jars are not showing LP fees in the apy breakdown. In some cases, this can be very substantial. 

Sushi's page on what these fees are does not exactly seem accurate. The fees themselves seem accurate but the percentage they have next to them seem a bit off.  But even still, our UI is not showing ANY lp fees in the APR for sushi / uniswap. It's only sushi reward tokens. 

Even tracing into the function that's supposed to add the daily LP fees (I think?) `getSushiPairDayAPY`, it doesn't seem to work the way it was expected to? After it queries the graph for the data, this is an excerpt of the result:

{"data":{"pairDayDatas":[{"pair":{"id":"**0x269db91fc3c7fcc275c2e6f22e5552504512811c**"},"reserveUSD":"2393641.952145832492224018925613596","volumeUSD":"106928.0678502322846893665467183976"},{"pair":{"id":"**0x269db91fc3c7fcc275c2e6f22e5552504512811c**"},"reserveUSD":"2504036.531082513023962311454570537","volumeUSD":"236824.672974688769003646485812937"},{"pair":{"id":"**0x269db91fc3c7fcc275c2e6f22e5552504512811c**"},"reserveUSD":"2347583.483670300446900031753870915","volumeUSD":"88952.49869973355941798436233027874"},{"pair":{"id":"**0x269db91fc3c7fcc275c2e6f22e5552504512811c**"},"reserveUSD":"2233423.003315021578083511648384892","volumeUSD":"665719.8234879982689881028503417846"},{"pair":{"id":"**0x269db91fc3c7fcc275c2e6f22e5552504512811c**"},"reserveUSD":"2318836.680087592009286081814761041","volumeUSD":"128671.0392579104317158532860705157"},{"pair":{"id":"**0x269db91fc3c7fcc275c2e6f22e5552504512811c**"},"reserveUSD":"2317505.675252081955351996230651443","volumeUSD":"95357.94792795641670875181095144785"},{"pair":

As you can see, the graph is returning different values with the same key. So the graph query must be very very wrong. But even if the query was fixed, I'm not convinced `useJarsWithApyEth` would be set up to handle it properly?

Anyway, this is a pretty big issue. In some cases, huge portions of the APY users can expect to earn just aren't showing at all.

**Comment by rawbdor** [comment]
Not replicatable
