### ISSUE TITLE
Smart network switching

### ISSUE THREAD

**Issue by robstryker** [pickle-finance/pickle-ui#137]
Switching from main net to polygon correctly tells metamask to switch networks. When switching back, it just tells us to do it ourselves. 

![image](https://user-images.githubusercontent.com/630383/132285173-10d41a4a-d6e7-44c3-8453-52054c5d9e1b.png)

Bad. Need Fixie.

**Comment by janklimo** [comment]
Good point, this has been bothering me as well

**Comment by janklimo** [comment]
This is the ultimate UX spotted on [Spooky Swap](https://spookyswap.finance/pools) we should implement – add the network with the click of a button:

<img width="367" alt="Screen Shot 2021-09-28 at 11 29 48" src="https://user-images.githubusercontent.com/7811733/135023498-73daec3c-2154-4d21-951f-5e38357ea0a0.png">
