### ISSUE TITLE
historic distribution of dill appears to have pickle/dill negative

### ISSUE THREAD

**Issue by rawbdor** [pickle-finance/pickle-ui#169]
This appears to be a presentation bug only. The numbers appear to be correct. 

![image](https://user-images.githubusercontent.com/90275425/135740913-62c36599-f6ef-4fe8-8bb1-1d39275aeb17.png)

The aqua-colored pickle-per-dill ratio appears to be in negative territory. Again, the numbers appear correct, but why it's presenting like this is questionable.

**Comment by janklimo** [comment]
This is because the last DILL amount is negative so the left y-axis starts in the negative territory. However, the PICKLE/DILL ratio series values are shown on the right y-axis.
