### ISSUE TITLE
"Daily Emission" on info/profit tab does not factor dill boosts

### ISSUE THREAD

**Issue by rawbdor** [pickle-finance/pickle-ui#171]
"Daily Emission" on info/profit tab does not factor dill boosts. This means it is using the farm's average rate. For people with little to no dill, the resulting value is about double what it should be.

**Comment by rawbdor** [comment]
```
                    <InfoCardContent
                      title={"Daily Emission"}
                      value={accountData ? accountData.earn : accountData}
```

You can see it comes from accountData.earn. This value is calculated by taking the values from api entrypoint `/prod/protocol/earnings/walletId` and taking the user's balanceUsd over the farm's balanceUsd and multiplying by the farm's pickle-per-day (as exposed on `protocol/farm` endpoint to get what fraction of the farm's emissions are going to the user.

This is just wrong, though. The values exposed on `protocol/farm` are average values and adjusted upwards for boosts or downwards for a lack of boosts.

**Comment by bcstryker** [comment]
v1 issue, will not be worked on
