### ISSUE TITLE
DILL feedback on commit 5e6f6a8

### ISSUE THREAD

**Issue by larrythecucumber321** [pickle-finance/pickle-ui#22]
List of items to work on per feedback from @mannyreimi88 in https://hackmd.io/XByWjrBhTCeXUa2zvJmxbw for PR #6.

### Group 1 - assigned to @0xkoffee 

- [x] on `/dill`, the actual DILL received upon locking does not reflect the estimates on the UI. The calculation should be fixed.
- [x] on `/dill`, radio button option should be given for extending lock time
- [x] on `/dill`, ensure that locking period on UI cannot exceed max imposed by contract (4 years)   

### Group 2 - assigned to @larrythecucumber321  

- [x] on  `'/gauge`, consider/apply the UI changes suggested by @mannyreimi88

**Comment by robstryker** [comment]
This issue appears out of date
