### ISSUE TITLE
Support new enablement flag closing-only

### ISSUE THREAD

**Issue by rawbdor** [pickle-finance/pickle-ui#245]
pfcore added an enablement flag for closing-only (as opposed to fully disabled) so that when a jar gets disabled, it doesn't suddenly disappear and go to the inactive jar section.

**Comment by rawbdor** [comment]
Closing-only flag should leave the jar in the main section, but disable the deposit and deposit-and-stake buttons. Also a message that the jar is in withdraw-only mode would be useful.

**Comment by janklimo** [comment]
@rawbdor none of the jars currently have this flag. Has it changed to `withdraw_only`?
