### ISSUE TITLE
Switch networks on click

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#254]
When a user clicks any of the menu items:

<img width="338" alt="Screen Shot 2022-01-07 at 09 48 09" src="https://user-images.githubusercontent.com/7811733/148483412-076f6193-ad4f-4d78-a5cb-f0037661ea96.png">

or items in the callout:

<img width="852" alt="Screen Shot 2022-01-07 at 09 47 54" src="https://user-images.githubusercontent.com/7811733/148483448-68ac1fc4-afb2-4f08-b01b-6b792a27a025.png">

trigger network switch.

**Comment by bcstryker** [comment]
partially fixed by #268
