### ISSUE TITLE
Connect button when on an unsupported network

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#273]
We can either hide the button or show a warning when the user is on an unsupported network.

<img width="370" alt="Screen Shot 2022-01-12 at 12 25 28" src="https://user-images.githubusercontent.com/7811733/149069029-c5e2730e-3340-4b5b-a976-553ba826f232.png">

**Comment by bcstryker** [comment]
I think an easier, and possibly more logical, fix is to leave the wallet connection displaying whatever it would normally display when you're connected, and instead change the highlighting and text on the network selection dropdown to say something like `Change Network` surrounded by red. That plus the `We're in a Pickle` pop-up should be clear enough.
![Screen Shot 2022-01-12 at 2 09 24 AM](https://user-images.githubusercontent.com/24856006/149080658-39db008d-5a77-4ad4-9f40-effc29b27e31.png)

**Comment by janklimo** [comment]
The problem with that is there is no address or avatar when you're not connected

**Comment by bcstryker** [comment]
@janklimo gotcha, do you think we need anything other than what is shown in the screen shot in my last comment? I think if the wallet is connected there's no issue with the wallet, and if the chain is not supported, the user should be alerted by the `We're in a pickle` pop-up and the network dropdown in the header will just display `Network settings`.

**Comment by bcstryker** [comment]
After fixing the issue with the unsupported network popup appearing on page load, this is now displaying the as a red "Connect Wallet" button on page load. I feel this should be considered while deciding what this button should look like in various states of loading and connectivity.
