### ISSUE TITLE
Create a brand new `LpIcon` type class or object, which is based on pfcore

### ISSUE THREAD

**Issue by bcstryker** [pickle-finance/pickle-ui#294]
I was really hoping, for this issue, that you'd try to create a brand new `LpIcon` type class or object, which is based on pfcore. 

For example, pass in a JarDefinition. The JarDefinition has a few key parts:  

1) The protocol. This could be the bigger image in the back
2) a deposit token, which has a set of 'components'

If the jar has one component (single-staking), you could overlay the single image on the bottom-right of the protocol image. 
If the jar has two components (LP), you would overlay the two component images. 
If the jar has three components (tricrypto etc), you would arrange 3 components in a triangle on the bottom right. 
etc etc etc. 

Re-using image code from v1 is risky.

_Originally posted by @robstryker in https://github.com/pickle-finance/pickle-ui/pull/293#discussion_r784588859_

**Comment by janklimo** [comment]
Quick comments on the design @bcstryker just shared (I'll call it Design A):

<img width="720" alt="optionA" src="https://user-images.githubusercontent.com/7811733/149646988-d295edbf-eb5e-456c-ae01-81c707bd1c95.png">

I'm seeing the following issues with this approach:

1. We're giving more space to the protocol than we do to tokens when, in fact, protocol is secondary when users make decisions about what to invest in. Besides, we already have protocol name below farm title. I think it makes sense to drop it to direct attention to tokens.
2. As @bcstryker mentioned, Design A will run into problems with 4+ tokens. They'll be very small if rendered in a row.
3. The design is more complex to implement/maintain while keeping it responsive.

To address the above, I'm proposing the following:

<img width="341" alt="Screen Shot 2022-01-16 at 11 08 53" src="https://user-images.githubusercontent.com/7811733/149647080-e01e91cf-36b4-41f3-a9a7-1ea45991a926.png">

- [x] A lot of space for token icons (no distractions with irrelevant elements)
- [x] Scales to N tokens
- [x] Simple to implement, responsive.
- [x] Format familiar to users from other apps (Zapper et al)

As next steps, we'll need to audit:

1. Pf-core returning components for all farms. E.g. Curve's tricrypto pool should show USDC, USDT, DAI as components. cc @bcstryker @rawbdor 
2. UI's token list. They'll need to be in decent resolution and matching backgrounds to look good with our standard round border. I'll do this.
