### ISSUE TITLE
Wrong network warning on page load

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#296]
When being connected to a supported network, on page load you can see the warning that you're on an unsupported network.

**Comment by larrythecucumber321** [comment]
@janklimo This problem stems from the `generateUserModel()` call in `UserModelProvider`. Specifically, the Aurora RPC provider (at https://mainnet.aurora.dev/) is very problematic in that I get blocked by a CORS error when it makes the call to the `pfcore` library to fetch users' Aurora balances, as shown below 
![image](https://user-images.githubusercontent.com/71284258/151244180-4890b6aa-4faf-403f-b13c-ed376b5be82f.png)

My workaround to this problem (which is obviously not workable), is to VPN to another location to make the Aurora RPC work, at which point the error goes away (and Aurora balances are successfully fetched). 
![image](https://user-images.githubusercontent.com/71284258/151244642-bcc4fd85-fb04-419d-9f7d-afbb9c0501ff.png)

Not too sure what can be done on our end.

**Comment by janklimo** [comment]
@larrythecucumber321 sorry if the description wasn't too clear. I was referring to the wrong empty/default state when loading the page. Here's what I see when I reload the page:

![emptystate](https://user-images.githubusercontent.com/7811733/151649425-c310ca6e-4daf-4ada-b771-0f91d0f0e13b.gif)

This is before we load user model.

@bcstryker might know what changed recently but we didn't have this in the original implementation of the callout card.
