### ISSUE TITLE
Fix joined farms list and dashboard data

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#298]
<img width="1496" alt="Screen Shot 2022-01-14 at 19 39 21" src="https://user-images.githubusercontent.com/7811733/149516876-4e29ec1f-8992-40ad-b0cb-76589b385c8e.png">

Two issues here:

1. I have some money in the WANNA/USDC farm but I'm not as rich as this suggests
2. I have a USDC balance but I'm not in the Yearn farm

**Comment by larrythecucumber321** [comment]
First issue fixed by [pickle-finance/pf-core#106](https://github.com/pickle-finance/pf-core/pull/106).

**Comment by larrythecucumber321** [comment]
Sorry, could have been a little more descriptive of the fix here. See https://github.com/pickle-finance/pickle-ui/pull/326 for the fix to the 2nd issue (having a deposit token balance shows you're in jar).

**Comment by janklimo** [comment]
Resolved as of #326
