### ISSUE TITLE
Fix max APY card

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#427]
<img width="568" alt="Screen Shot 2022-04-09 at 18 53 18" src="https://user-images.githubusercontent.com/7811733/162573013-11282c10-02de-4922-93ca-ef719797da86.png">

This currently doesn't match what you see in Farms when you sort by APY

**Comment by larrythecucumber321** [comment]
Is resolved with https://github.com/pickle-finance/pickle-ui/commit/1cf273646a0174b971c50d33566a55a788b87bd2 and resolution of #440

**Comment by janklimo** [comment]
Done in #440
