### ISSUE TITLE
Low TVL jars look like bad investments.

### ISSUE THREAD

**Issue by mannyreimi88** [pickle-finance/pickle-ui#437]
**When** users see a new jar/farm on our UI which has low TVL
**I want to** help them feel less anxious about being among the first to join in
**So I can** kickstart the liquidity of new jars faster

---

- [ ] the "liquidity" column SHOULD NOT display zeroes or low liquidity numbers (less than $10,000 on sidechains and less than $100,000 on mainnet) when Jars are new (like less than 30 days old).
- [ ] it is RECOMMENDED the "liquidity" column instead display something like "NEW!"
- [ ] it is RECOMMENDED that the real liquidity data is instead provided on hover on Jars with low liquidity.

---

<img width="1151" alt="zero-on-liquidity" src="https://user-images.githubusercontent.com/60312391/163311984-1eea2678-a833-4244-b48c-469b5a611ca0.png">

**Comment by janklimo** [comment]
Upon new Jar launch for up to 1 month: Display TVL as "NEW"
If TVL passes $10k during the first month: Display TVL as the actual number
If 1 month passes and TVL below $1k: Display TVL as "<$1k"
For all Jars with over $1k TVL more than 1 month after launch: Display TVL as as the actual number
For all Jars with under $1k TVL: Display TVL as "<$1k"
