### ISSUE TITLE
Dill APY

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#442]
https://github.com/pickle-finance/pickle-ui/blob/9222c728271cbcdd51b82a98c007dc4882759600/v2/features/dill/RevenueStats.tsx#L63-L66

**Comment by janklimo** [comment]
Might as well implement some ideas from [this comment](https://github.com/pickle-finance/pickle-ui/discussions/390#discussioncomment-2553132).

**Comment by larrythecucumber321** [comment]
closed with https://github.com/pickle-finance/pickle-ui/commit/8ca791d7eb741b9e960e4bcfa4439d60ca39ede7 - I'll let @mannyreimi88 open issues for the other items
