### ISSUE TITLE
issues found when Alpha Testing on 12-APR-2022 

### ISSUE THREAD

**Issue by mannyreimi88** [pickle-finance/pickle-ui#443]
- [x] add the $PICKLE balance in-wallet and the $PICKLEs locked in the current $DILL lock (and maybe their worth in $) so it's easy to grasp if I need to lock anything.
<img width="307" alt="how-many-pickles" src="https://user-images.githubusercontent.com/60312391/162998062-29278d3f-6ed4-46a3-9511-9eb4619b9fd4.png">

- [ ] ~~may need buttons to refresh balances in modals, this is because I am sure my balance changed while the page was already loaded but I had to refresh the whole page as when I clicked the modal by balance was zero.~~
<img width="449" alt="refresh-button" src="https://user-images.githubusercontent.com/60312391/162998546-5923ccd6-c185-4c42-afe7-2b6b32af6910.png">

- [x] `increase_amount()` call failed: https://etherscan.io/tx/0x75d57d3c1c9d45baa98f89bacf79b35b34635f15f8f1b3958ec1fb892795e92b
- [x] extend lock modal opens and default state seems there's a visual bug.
<img width="446" alt="slider-visual-bug-increase-lock" src="https://user-images.githubusercontent.com/60312391/162998820-80ad4d42-bc17-4847-9c79-bc41124383d4.png">

- [ ] I was unsure whether I was extending lock for the max amount or not.
<img width="449" alt="max-lock-label" src="https://user-images.githubusercontent.com/60312391/162999376-8a3d6e61-b12c-4ee1-bc7c-90d2f7bbd2e2.png">

- [ ] extend lock transaction couldn't be even relayed
<img width="405" alt="increase_unlock_time_total_fail" src="https://user-images.githubusercontent.com/60312391/163000295-96bc339e-0fbc-4237-9b2e-f33d0965c2c1.png">

- [x] gas estimates were off throughout
<img width="134" alt="gas-estimates-off" src="https://user-images.githubusercontent.com/60312391/162999523-94456863-fc1c-4ffa-bc44-1ae465f2ff62.png">

- [x] more indicators are needed in the revenue distribution stats element
<img width="931" alt="revenue-stats-changes" src="https://user-images.githubusercontent.com/60312391/163000505-52154f6c-50be-496f-a969-a501afaf59e6.png">

- [ ] another cosmetic improvement would be if the "pie chart" image here we could use the "identicons" by Dan Finlay that are very classic to Ethereum https://www.npmjs.com/package/ethereum-identicon
<img width="171" alt="Screenshot 2022-04-13 at 1 10 44 AM" src="https://user-images.githubusercontent.com/60312391/163017091-49bf5920-edf8-4389-8a58-d23ccb4ed089.png">

**Comment by larrythecucumber321** [comment]
Implemented in #457

Comments:
- I don't think the "Max" button is needed. 4 years/end of slider is obvious max imo
- Extend lock failing is due to a MM issue, please try it again
- Gas estimates out of scope
- Revenue share stats
  - APY breakdown will be done as part of ve(3,3) PR
  - Average lock duration added
  - APR is already projected
  - PE/PS not necessary imo (not aware of other defi protocols doing this)

See deployment here https://pickle-ui-git-fix-v2-dill-picklefinance.vercel.app/

**Comment by janklimo** [comment]
Gas prices fixed in #465
