### ISSUE TITLE
Show correct available interactions with jars without farms

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#462]
I originally hid the PICKLEs earned card for these jars but just realized the stake card shouldn't be there either:

<img width="1473" alt="Screen Shot 2022-04-25 at 22 35 18" src="https://user-images.githubusercontent.com/7811733/165123380-efb7ebb2-e7f1-4378-a181-d6fcbcc00722.png">

Possible approach:

<img width="1476" alt="Screen Shot 2022-04-25 at 22 44 01" src="https://user-images.githubusercontent.com/7811733/165124855-eabad2d4-7d96-4199-9c7c-bce3d3ff07bf.png">

Sort of works but it also makes these jars look less desirable. Need a way to fill that space somehow 🤔

**Comment by janklimo** [comment]
@mannyreimi88 how would you approach the UI for jars without farms?

**Comment by bcstryker** [comment]
@Cruelladere do you have any ideas here? The app currently displays the farm row like the second picture above without the text next to it. There is no issue with functionality, just how it looks. Maybe you can take a stab at this?

**Comment by Cruelladere** [comment]
Thank you for the heads up @bcstryker,

Let's bring it up during Sprint Planning tomorrow :)

**Comment by Cruelladere** [comment]
@bcstryker 
I discussed with LKJ regarding this. aditya and him are planning on a flow that allow users to vote on the jars without farms getting gauges in GaugeProxyV2. 
I think it is ok to leave it blank in the mean time.
<img width="1066" alt="Screen Shot 2022-08-31 at 11 42 29" src="https://user-images.githubusercontent.com/92246406/187588340-03c10186-ae37-4d05-a0d6-b8737a5aa51c.png">

**Comment by bcstryker** [comment]
nothing to do here
