### ISSUE TITLE
Add missing navigation

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#470]
- [x] link to dill vote
- [x] do not open stats in a new tab
<img width="225" alt="Screen Shot 2022-05-01 at 18 27 12" src="https://user-images.githubusercontent.com/7811733/166143851-ec54a176-9c98-4b5f-b82d-5e61c504e884.png">

**Comment by janklimo** [comment]
@bcstryker I suggest we make the link to vote a top-level link something like

<img width="215" alt="Screen Shot 2022-05-03 at 13 45 59" src="https://user-images.githubusercontent.com/7811733/166414046-8bd2d2c3-3144-4c83-9def-022cc1022b15.png">

to keep the navbar consistent.

**Comment by bcstryker** [comment]
<img width="1546" alt="Screen Shot 2022-05-10 at 12 00 10 PM" src="https://user-images.githubusercontent.com/24856006/167672040-9946dc7f-933e-496d-8f52-60f2f44b5e7d.png">

Vote navigation added
