### ISSUE TITLE
Visual chain filter element

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#471]
Something like

<img width="1265" alt="Screen Shot 2022-05-01 at 18 51 22" src="https://user-images.githubusercontent.com/7811733/166144565-b1165410-696e-414e-84ec-4aee5c27d57f.png">

**Comment by bcstryker** [comment]
@janklimo is this to filter the farms table?

**Comment by janklimo** [comment]
@larrythecucumber321 @bcstryker do you think this is a good idea? It's nice to have, but I don't want the UI feel too much like other services.

**Comment by larrythecucumber321** [comment]
@janklimo yes I think this is a good feature for us to have. Currently, there's some friction in filtering for the jars on my current chain. This will make it easier (and even more so if we set defaults based on their connected network, etc).
