### ISSUE TITLE
Connect to Metis and Optimism broken

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#479]
This button isn't working:

<img width="1792" alt="Screen Shot 2022-05-04 at 21 13 32 PM" src="https://user-images.githubusercontent.com/7811733/166700204-3108103f-158c-4054-ad23-3c0e46b02cd1.png">

**Comment by bcstryker** [comment]
@janklimo hey I tested this today and it worked fine. Not sure if someone fixed it in another merge or something but I believe this issue should not be open anymore.

**Comment by janklimo** [comment]
This is still broken, also for Optimism. Using the network dropdown, I get these errors when trying Metis and Optimism:

<img width="1194" alt="Screen Shot 2022-05-27 at 11 49 38" src="https://user-images.githubusercontent.com/7811733/170631467-df20f276-32b0-493d-be42-f50b4b272aa0.png">
