### ISSUE TITLE
Dill approaching expiration discrepancies

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#530]
<img width="390" alt="Screen Shot 2022-06-17 at 15 29 12" src="https://user-images.githubusercontent.com/7811733/174259404-8605696d-c9fa-466d-ba35-19f68b013899.png">

Still got some DILL apparently:

<img width="283" alt="Screen Shot 2022-06-17 at 15 29 54" src="https://user-images.githubusercontent.com/7811733/174259509-d002ac77-3ba3-4f7a-b307-9407d6f8c371.png">

**Comment by bcstryker** [comment]
this is in the wrong place
