### ISSUE TITLE
Dill page innefficient, could avoid 20+ http requests?

### ISSUE THREAD

**Issue by robstryker** [pickle-finance/pickle-ui#56]
https://github.com/pickle-finance/pickle-ui/blob/0c5bdcc4b2a670cd0881e52a9a025869eed9b1e1/containers/DILL/useProtocolIncome.ts#L17

In an attempt to get the weekly revenue projections, the dill page first accesses `https://stkpowy01i.execute-api.us-west-1.amazonaws.com/prod/protocol/pools` to get a list of jars + farms and their apy. 

This response includes the following:
```
identifier    "alcx-eth"
liquidity_locked    26180312.73
apy    175.25
```
The `apy` listed here matches the 3-day-farm apy from `https://stkpowy01i.execute-api.us-west-1.amazonaws.com/prod/protocol/jar/alcx-eth/performance`

The dill page then iterates through these assets and runs a separate request to the above performance url in order to fetch the 3-day JAR apy (which is NOT included in the original request). The number of requests done here is equal to the number of jar assets that were returned in the first request. The dill page then does math on this to get the revenues. 

These 20+ requests could be completely avoided if `prod/protocol/pools` returned both the 3-day farm apy AND the 3-day jar apy.

**Comment by axejintao** [comment]
@larrythecucumber321 we should prioritize this issue and get it launched asap + ui fixes corresponding to this change. 
this issue is the one that i had mentioned which makes the aws bill more expensive each month to do high call volume on those performance endpoints.
